name: Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Configure
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      shell: cmd
      run: |
        cd tests
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd tests
        cmake --build build -j4 --config Release
