name: Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest
    env:
      VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Configure
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      shell: cmd
      run: |
        call "%VCVARS%"
        cd tests
        cmake -S. -Bbuild -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        call "%VCVARS%"
        cd tests
        cmake --build tests/build -j4
